---
sidebar: sidebar 
permalink: concept-replication.html 
keywords: ontap, cluster, discover, manage, BlueXP, bluexp, hybrid cloud, replication policy, policy, replication, replicating, snapmirror, snapvault, data replication, fanout, cascade, source, destination, disaster recovery, DR, archive, archiving, retention, netapp replication 
summary: NetApp SnapMirror replica datos a altas velocidades a través de LAN o WAN, de modo que obtiene alta disponibilidad de datos y una rápida replicación de datos en entornos virtuales y tradicionales.  Cuando replica datos a sistemas de almacenamiento NetApp y actualiza continuamente los datos secundarios, sus datos se mantienen actualizados y permanecen disponibles siempre que los necesite. No se requieren servidores de replicación externos. 
---
= Obtenga más información sobre la NetApp Replication
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp SnapMirror replica datos a altas velocidades a través de LAN o WAN, de modo que obtiene alta disponibilidad de datos y una rápida replicación de datos en entornos virtuales y tradicionales.  Cuando replica datos a sistemas de almacenamiento NetApp mediante NetApp Replication y actualiza continuamente los datos secundarios, sus datos se mantienen actualizados y permanecen disponibles siempre que los necesite. No se requieren servidores de replicación externos.



[[netapp-console]]
== NetApp Console

Se puede acceder a NetApp Replication a través de la NetApp Console.

La consola ofrece una gestión centralizada de los servicios de almacenamiento y datos de NetApp en entornos locales y en la nube, con un nivel de clase empresarial. La consola es necesaria para acceder y utilizar los servicios de datos de NetApp. Como interfaz de gestión, permite gestionar numerosos recursos de almacenamiento desde una única interfaz. Los administradores de la consola pueden controlar el acceso al almacenamiento y a los servicios de todos los sistemas de la empresa.

No necesitas ninguna licencia ni suscripción para empezar a utilizar la Consola. Solo incurres en cargos cuando necesitas implementar agentes de la Consola en tu nube para garantizar la conectividad con tus sistemas de almacenamiento o los servicios de datos de NetApp. Sin embargo, algunos servicios de datos de NetApp accesibles desde la Consola requieren licencia o suscripción.

Obtén más información sobre el https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp Console"].



[[features]]
== Funciones

* Replique datos entre sistemas de almacenamiento ONTAP para respaldar la copia de seguridad y la recuperación ante desastres en la nube o entre nubes.
* Garantice la confiabilidad de su entorno de DR con alta disponibilidad.
* La replicación eficiente a nivel de bloque entre sistemas de almacenamiento ONTAP es rápida y eficaz, con puntos de recuperación granulares tanto para la recuperación ante desastres como para el backup.




[[cost]]
== Costo

NetApp no ​​le cobra por usar NetApp Replication, pero deberá consultar con su proveedor de nube para conocer los cargos de ingreso y egreso de datos aplicables.



[[supported-systems]]
== Sistemas compatibles

NetApp Replication permite la replicación de datos entre los siguientes tipos de sistemas.

[cols="30,30"]
|===
| Sistema fuente | Sistemas de destino compatibles 


| Cloud Volumes ONTAP  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* clúster ONTAP local




| clúster ONTAP local  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* clúster ONTAP local




| Amazon FSx para ONTAP  a| 
* Amazon FSx para ONTAP
* Cloud Volumes ONTAP
* clúster ONTAP local


|===


[[how-data-replication-works]]
== Cómo funciona la replicación de datos

NetApp Replication simplifica la replicación de datos entre volúmenes en sistemas ONTAP independientes usando las tecnologías SnapMirror y SnapVault. Para configurar la replicación, solo tienes que identificar el volumen de origen y el volumen de destino, y luego elegir una política de replicación y una programación.

Para Cloud Volumes ONTAP, NetApp Replication compra los discos necesarios, configura las relaciones, aplica la política de replicación y luego inicia la transferencia de referencia entre volúmenes.


NOTE: La transferencia de línea base incluye una copia completa de los datos de origen.  Las transferencias posteriores contienen copias diferenciales de los datos de origen.



[[supported-data-protection-configurations]]
== Configuraciones de protección de datos admitidas

NetApp Replication admite configuraciones de protección de datos simples, en abanico y en cascada:

* En una configuración simple, la replicación ocurre del volumen A al volumen B.
* En una configuración de abanico, la replicación se produce desde el volumen A a múltiples destinos.
* En una configuración en cascada, la replicación ocurre del volumen A al volumen B y del volumen B al volumen C.




[[replicate-data-using-netapp-backup-and-recovery]]
== Replique datos utilizando NetApp Backup and Recovery

link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["NetApp Backup and Recovery"^] te permite replicar datos entre volúmenes en sistemas ONTAP independientes y, al mismo tiempo, crear copias de seguridad de esos mismos datos en almacenamiento de objetos. Si quieres gestionar tanto la replicación como la protección de backup a objeto para los mismos datos de ONTAP en un solo servicio, considera usar NetApp Backup and Recovery.

NetApp Replication admite las siguientes funciones que no están disponibles en Backup and Recovery.

* Actualmente, NetApp Backup and Recovery no admite la replicación de datos hacia o desde sistemas FSx for ONTAP.
* NetApp Backup and Recovery no permite crear una replicación puntual de un volumen.


Además, las relaciones en cascada son más fáciles de configurar en Replication. Si necesitas alguna de estas funciones, utiliza NetApp Replication.
